ALTER TABLE prototypes
ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE comments
ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;
